//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiLAGen.Client
{
    
    
    [Tecan.Sila2.SilaFeatureAttribute(true, "contracts")]
    [Tecan.Sila2.SilaIdentifierAttribute("TestService")]
    [Tecan.Sila2.SilaDisplayNameAttribute("Test Service")]
    public partial interface ITestService
    {
        
        void Initialize();
    }
}
